### ISSUE TITLE
[QUESTION] Batch 7, Grantee - SunDAO

### ISSUE THREAD

**Issue by gaiaus** [gaiaus/aadao#1]
On April 10th, 2024, the Grants SubDAO made a "milestone" [$37,200 USDC payment](https://daodao.zone/dao/neutron10xwzc88kefwtlup9c2tmw4mj4ng7u79g8lsapp0c9jc02xt247zqwzzghf/proposals/A26) to "SunDAO."

The summary provided for the transaction states:

"_The recent milestone payment for SunDAO, an investment DAO awarded a grant from AADAO, is attributed to their successful attainment of set objectives. This includes establishing connections with Cosmos protocols, startups, and VCs to solicit input and feedback, refining their budget and business plan, creating an investment deck, and identifying potential investors such as VCs, DAOs, Fund of Funds, and Grant Organizations. These accomplishments underscore SunDAO's commitment to leveraging the grant to bootstrap their operations effectively._"

The information on DaoDao also refers to the grantee as applicant 156 from Batch 7. However, in all transparency reports since Batch 7 grantees were announced, SunDAO has not been referenced by name. There are only references to funding for "new DAO bootstrapping" with an approved allocation of $250,000.

Questions:

* Can AADAO confirm that the $37,200 payment to SunDAO pertains to the spending approved for DAO bootstrapping?

* Can AADAO avoid using non-descriptive project names and instead provide descriptive project names, along with identifying the project team and project lead associated with each grant consistently across all public reports?

* Are there any other DAO projects approved for funding under the "new DAO bootstrapping" allocation?

**Comment by syedc5** [comment]
Could you point me to where you saw the "new DAO bootsrapping $250k approved". That's definitely a mistake. 

$124k was the actual approved amount.

wrt to the questions:
- Yes, the $37.2k on Apr 10 was for SunDAO. In the context of the transparency report and older comms, "new DAO bootstraping" refers to SunDAO (excluding mandate renewal forum discussions from this - cause that forum thread has convos around BD DAO, etc)
- Agreed! Hoping you can help with this too
- No, all "new DAO bootstrapping" mentions refer to SunDAO

To add more confusion to the mix, FYI on [Transparency Report 6](https://www.atomaccelerator.com/blog/transparency-report-6), we have mentioned "SunDAO" correctly in the Grant Updates section, but kept the name "New DAO boostraping" in the annex.

This will be corrected in the next report

**Comment by gaiaus** [comment]
Thank you for the clarification @syedc5 !

**Comment by gaiaus** [comment]
Batch 7, 2023, New DAO Bootstrapping has been updated as such
![Screenshot_20240627-185631.png](https://github.com/gaiaus/aadao/assets/146326929/76479bc4-2f9c-45d6-b899-63df18146e55)
